name: dart_fitness_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
    hive: ^2.0.4
    path: ^1.8.0
    path_provider: ^2.0.14

dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
